"""Rule tables for deterministic tone and behavior signals."""

from __future__ import annotations

UNCERTAINTY_RULES = (
    {
        "pattern": r"\bmay\b|\bmight\b|\bcould\b",
        "matched_phrase": "modal uncertainty",
        "signal_type": "hedging_modal",
        "strength": 1,
        "notes": "Weak modal hedge.",
    },
    {
        "pattern": r"\bcontinue to monitor\b",
        "matched_phrase": "continue to monitor",
        "signal_type": "monitoring_language",
        "strength": 2,
        "notes": "Management explicitly signaled continued monitoring.",
    },
    {
        "pattern": r"\bsubject to\b",
        "matched_phrase": "subject to",
        "signal_type": "conditional_language",
        "strength": 2,
        "notes": "Management qualified the statement with a condition.",
    },
    {
        "pattern": r"\bvisibility (?:remains|is) limited\b|\blimited visibility\b",
        "matched_phrase": "limited visibility",
        "signal_type": "visibility_constraint",
        "strength": 3,
        "notes": "Management explicitly said visibility was limited.",
    },
    {
        "pattern": r"\bdifficult to predict\b|\bhard to predict\b",
        "matched_phrase": "difficult to predict",
        "signal_type": "prediction_difficulty",
        "strength": 3,
        "notes": "Management explicitly said the outcome was difficult to predict.",
    },
    {
        "pattern": r"\btiming uncertainty\b|\buncertain timing\b",
        "matched_phrase": "timing uncertainty",
        "signal_type": "timing_uncertainty",
        "strength": 3,
        "notes": "Management explicitly flagged timing uncertainty.",
    },
    {
        "pattern": r"\bmacro(?:economic)? uncertainty\b",
        "matched_phrase": "macro uncertainty",
        "signal_type": "macro_uncertainty",
        "strength": 3,
        "notes": "Management explicitly referenced macro uncertainty.",
    },
)

REASSURANCE_RULES = (
    {
        "pattern": r"\bremain(?:s)? confident\b|\bwe remain confident\b",
        "matched_phrase": "remain confident",
        "strength": 3,
        "topic_hint": "confidence",
        "notes": "Explicit management confidence language.",
    },
    {
        "pattern": r"\bdemand remains strong\b|\bdemand is strong\b",
        "matched_phrase": "demand remains strong",
        "strength": 2,
        "topic_hint": "demand",
        "notes": "Management explicitly framed demand as strong.",
    },
    {
        "pattern": r"\bfundamentals remain intact\b|\bour fundamentals remain intact\b",
        "matched_phrase": "fundamentals remain intact",
        "strength": 2,
        "topic_hint": "fundamentals",
        "notes": "Management explicitly said fundamentals remain intact.",
    },
    {
        "pattern": r"\bpipeline remains healthy\b|\bour pipeline remains healthy\b",
        "matched_phrase": "pipeline remains healthy",
        "strength": 2,
        "topic_hint": "pipeline",
        "notes": "Management explicitly framed the pipeline as healthy.",
    },
    {
        "pattern": r"\bwell positioned\b|\bwe are well positioned\b",
        "matched_phrase": "well positioned",
        "strength": 3,
        "topic_hint": "positioning",
        "notes": "Management explicitly said the company is well positioned.",
    },
    {
        "pattern": r"\bremain(?:s)? on track\b|\bwe remain on track\b",
        "matched_phrase": "remain on track",
        "strength": 3,
        "topic_hint": "execution",
        "notes": "Management explicitly said execution remains on track.",
    },
    {
        "pattern": r"\bencouraged by\b",
        "matched_phrase": "encouraged by",
        "strength": 1,
        "topic_hint": "momentum",
        "notes": "Management used mild reassurance language.",
    },
)

SKEPTICISM_RULES = (
    {
        "pattern": r"\bi\s+was\s+just\s+wondering\s+if\s+you\s+could\b",
        "matched_phrase": "i was just wondering if you could",
        "strength": 1,
        "topic_hint": "clarification",
        "notes": "Analyst used a gentle but probing setup.",
    },
    {
        "pattern": r"\bwould\s+create\s+tough\s+comps\b",
        "matched_phrase": "would create tough comps",
        "strength": 1,
        "topic_hint": "comparability",
        "notes": "Analyst lightly challenged comparability assumptions.",
    },
    {
        "pattern": r"\bwhat(?:'s| is)\s+driving\b",
        "matched_phrase": "what's driving",
        "strength": 1,
        "topic_hint": "driver",
        "notes": "Analyst asked what is driving the result.",
    },
    {
        "pattern": r"\bi(?:'d| would)\s+be\s+curious\b",
        "matched_phrase": "i'd be curious",
        "strength": 1,
        "topic_hint": "clarification",
        "notes": "Analyst framed the question as a light probe.",
    },
    {
        "pattern": r"\bcould\s+you\s+just\s+talk(?:\s+a\s+little\s+bit)?\s+about\b",
        "matched_phrase": "could you just talk about",
        "strength": 1,
        "topic_hint": "clarification",
        "notes": "Analyst asked for additional explanation.",
    },
    {
        "pattern": r"\bwhere\s+are\s+you\s+on\s+that\b",
        "matched_phrase": "where are you on that",
        "strength": 1,
        "topic_hint": "status_check",
        "notes": "Analyst asked for a direct status update.",
    },
    {
        "pattern": r"\bhelp\s+us\s+understand(?:\s+why)?\b",
        "matched_phrase": "help us understand why",
        "strength": 2,
        "topic_hint": "clarification",
        "notes": "Analyst explicitly challenged the reasoning.",
    },
    {
        "pattern": r"\bwhat changed\b",
        "matched_phrase": "what changed",
        "strength": 2,
        "topic_hint": "change_driver",
        "notes": "Analyst explicitly asked what changed.",
    },
    {
        "pattern": r"\bwhy should we believe\b",
        "matched_phrase": "why should we believe",
        "strength": 3,
        "topic_hint": "credibility",
        "notes": "Analyst explicitly challenged management credibility.",
    },
    {
        "pattern": r"\bisn'?t that inconsistent\b",
        "matched_phrase": "isn't that inconsistent",
        "strength": 3,
        "topic_hint": "consistency",
        "notes": "Analyst explicitly called out inconsistency.",
    },
    {
        "pattern": r"\bare you seeing weakness\b",
        "matched_phrase": "are you seeing weakness",
        "strength": 2,
        "topic_hint": "demand",
        "notes": "Analyst explicitly probed for weakness.",
    },
    {
        "pattern": r"\bwhat gives you confidence\b",
        "matched_phrase": "what gives you confidence",
        "strength": 1,
        "topic_hint": "confidence",
        "notes": "Analyst asked management to justify confidence.",
    },
    {
        "pattern": r"\bwhat\s+gives\s+you\s+confidence\s+that\b",
        "matched_phrase": "what gives you confidence that",
        "strength": 4,
        "topic_hint": "confidence",
        "notes": "Analyst explicitly challenged the basis for management confidence.",
    },
    {
        "pattern": r"\bhow sustainable is that\b",
        "matched_phrase": "how sustainable is that",
        "strength": 2,
        "topic_hint": "sustainability",
        "notes": "Analyst questioned durability.",
    },
    {
        "pattern": r"\bhow\s+sustainable\s+do\s+you\s+think\b",
        "matched_phrase": "how sustainable do you think",
        "strength": 5,
        "topic_hint": "sustainability",
        "notes": "Analyst explicitly challenged how durable the trend is.",
    },
    {
        "pattern": r"\bwhat(?:'s| is)\s+the\s+timeline\s+to\b|\btimeline\s+to\s+realizing\b",
        "matched_phrase": "what's the timeline to",
        "strength": 2,
        "topic_hint": "timeline",
        "notes": "Analyst pressed on the timing of realization.",
    },
    {
        "pattern": r"\bpathway\s+to\s+closing\b|\bclosing\s+that\s+gap\b",
        "matched_phrase": "pathway to closing the gap",
        "strength": 2,
        "topic_hint": "execution",
        "notes": "Analyst pressed on how the execution gap will close.",
    },
    {
        "pattern": r"\bare\s+you\s+seeing\s+any\s+cannibalization\b",
        "matched_phrase": "are you seeing any cannibalization",
        "strength": 2,
        "topic_hint": "weakness",
        "notes": "Analyst probed for demand displacement.",
    },
    {
        "pattern": r"\bhow\s+long\s+will\b.*\bimpact\b",
        "matched_phrase": "how long will this impact",
        "strength": 2,
        "topic_hint": "constraint",
        "notes": "Analyst pressed on the duration of a constraint.",
    },
    {
        "pattern": r"\bare\s+you\s+confident\b",
        "matched_phrase": "are you confident",
        "strength": 2,
        "topic_hint": "confidence",
        "notes": "Analyst challenged management confidence directly.",
    },
    {
        "pattern": r"\bwhy\s+wouldn'?t\s+that\s+be\b|\bwhy\s+would\s+it\s+be\s+undermining\b",
        "matched_phrase": "why wouldn't that be",
        "strength": 5,
        "topic_hint": "durability",
        "notes": "Analyst strongly challenged strategic durability.",
    },
    {
        "pattern": r"\breverse\s+that\s+in\s+future\s+quarters\b|\bwhat\s+could\s+be\s+things\s+that\s+you\s+could\s+do\s+to\s+reverse\s+that\b",
        "matched_phrase": "reverse that in future quarters",
        "strength": 5,
        "topic_hint": "remediation",
        "notes": "Analyst pressed management on how to reverse the weakness.",
    },
    {
        "pattern": r"\bshould we think about this as weaker\b",
        "matched_phrase": "should we think about this as weaker",
        "strength": 3,
        "topic_hint": "weakness",
        "notes": "Analyst explicitly asked if the situation should be read as weaker.",
    },
)

QUESTION_PATTERNS = (
    r"\?$",
    r"\bcould you\b",
    r"\bcan you\b",
    r"\bcan you tell us\b",
    r"\bcould they\b",
    r"\bcould we\b",
    r"\bmay we\b",
    r"\bhave you\b",
    r"\bwould you\b",
    r"\bshould we\b",
    r"\bhow do you\b",
    r"\bi was just wondering\b",
    r"\bi(?:'m| am| was) (?:just )?curious\b",
    r"\bi(?:'d| would) like to\b",
    r"\bif i could\b",
    r"\bmaybe you could\b",
    r"\bmaybe we could\b",
    r"\bi'?m curious\b",
    r"\bif you could\b",
    r"\bwhat that might mean\b",
    r"\band i think you could\b",
    r"\bwhere do you think\b",
    r"\bwhat might\b",
    r"\bwhat about\b",
    r"\bhelp us understand why\b",
    r"\bwhat changed\b",
    r"\bwhy should we believe\b",
    r"\bisn'?t that inconsistent\b",
    r"\bare you seeing weakness\b",
    r"\bwhat gives you confidence\b",
    r"\bhow sustainable is that\b",
    r"\bshould we think about this as weaker\b",
)

OPERATOR_PATTERNS = (
    r"^operator\b",
    r"\byou may begin\b",
    r"\byou may access the replay system\b",
    r"\byou may now disconnect\b",
    r"\byou may register to ask a question\b",
    r"\byou may press star\b",
    r"\bthis call may be recorded\b",
    r"\bcould we get the next question\b",
    r"\bour next question\b",
    r"\bnext question comes from\b",
    r"\bplease go ahead\b",
)

BOILERPLATE_PATTERNS = (
    r"\bforward-looking\b",
    r"\bactual results may differ materially\b",
    r"\bsec filings\b",
    r"\bwritten permission\b",
    r"\bmay not be recorded\b",
    r"\bnot promises or guarantees\b",
)

TOPIC_PATTERNS = {
    "guidance": ("guidance", "outlook", "forecast"),
    "revenue": ("revenue", "sales", "arr"),
    "margin": ("margin", "profitability", "ebitda"),
    "demand": ("demand", "bookings", "orders"),
    "pipeline": ("pipeline", "backlog"),
    "macro": ("macro", "macroeconomic"),
    "execution": ("execution", "on track"),
}
